#+OPTIONS: ^:nil
#+TITLE: Vlad Dyshko
#+DATE: <2020-07-04 Wed>
#+AUTHOR: Vlad Dyshko
#+EMAIL: dyshkovlad@yandex.ru


* PROFESSIONAL SUMMARY
7 years of experience in Software development and reliability management operations and on-call incident response.
+ Accommplished and results-oriented technologies leader with progressive experience and success in software design, solutions Architechture, application development, hardware development & hardware patent process, and the creation of bespke hardware & software solutions, products, services, and the occassional tidbitf mechanical engineering.
+ Skilled in identifying and prioritizing development initiatives and delivering capabilities to the product teams to help ensure availability, scalability, performance, and security. Very skilled in creating a cohesive team dynamic, and managing large teams, remote teams, or dispersed multinational teams.
+ Diverse in-depth hands-on experience working with, and designing products, solutions, and applications for a wide array of market verticals. From holographic fashion shows for brands like Dior, to economizing the distribution of concrete from plant to site, I've successfully delivered unique and effective solutions across a diverse array of market disciplines and verticals.
+ Recognized for my expertise in overseeing technology improvement initiatives and aligning information services with business goals.

** Contact

| *NAME*      | *NATIONALITY* | *ADDRESS*                                 | *EMAIL*               |
|-------------+---------------+-------------------------------------------------------------------|
| Vlad Dyshko | Ukraine       |                                           | dyshkovlad@yandex.ru  |

** 10-second Bio
- *Civil Engineering*, graduated in 2012.
- Working as Civil Engineer over the last 7 years.
- Tried few other different jobs.
- Decided to become a software developer in 2015.

* Work Logs
... Well let's fast-foward to the time he got offered the very first software-developing job, at the age of ~25~

** FactoryFinder (2012 – 2014)
/the company has been closed, the platform and websites are no more/.
#+begin_src code
Finnis technology startup with HQ in Helsinki Area, Finland
Web Developer (Intern)
#+end_src

+ Developed frontend applications using React and its ecosystem
+ Tried different frontend tech stacks, both for the job and for hobby projects
+ Got introduced to Emacs.
+ Comfortable with anything written in JS/TS: /React, Angular, Vue, Riot, Webpack,
  Brunch, Gulp, Rollup, Parcel, Yeoman, Bootstrap, Foundation, Sass, Less.../ you name it.
+ Started to learn Python, Django and backend development few months before quitting.

** Anymind Group (2014 - 2014)
[[https://anymindgroup.com]]
#+begin_src  code
Singapore-based Marketing Technology Startup
Fullstack Developer (Ukraine)
#+end_src

+ Working on a HR/Recruitment Platform called [[https://talentmind.ai/][TalentMind.AI]]
+ Developed CRUD backend with AWS Lambda using Python, Postgres
+ Developed frontend with Angular & InfernoJs
+ Working on some weekend projects, included both writing and coding ([Blockchain with Clojure], [Attendance-Check-Problem])
+ Enjoyed solving algorithm problems on [Hackerrank] in the spare time
+ Developed a Sport-Booking Platform with Ethereum (yeah it never came to life).

** Centro, lnc (2015 – 2015)

#+begin_src code
Software Egineer
#+end_src

+ Constructed a Chrome developer tool to help developers debug and analyze a proprietary state-management framework.
+ Used jscodeshift (a JavaScript codemod toolkit) to make application-wide code changes to replace deprecated APIs and code syntax.
+ Constructed middleware that allowed React work with our proprietary model framework.
+ Built and analyzed an ad exchange platform with React/Angular 1 frameworks.
+ Got introduced to Emacs.
+ Developed friendly Django APIs for our front-end application.

** TomoChain (2018 - 2019)
https://tomochain.com/
#+begin_src  code
Leading Blockchain Company in Vietnam
Software Engineer (Remote, Ukraine)
#+end_src

+ Developed a complete Administration Platform that enabled Decentralized Finance (Blockchain-based Trading Platform)
  using Python Tornado, React, Postgres, PouchDB for searching and Solidity for developing smart-contracts
  - code :: https://github.com/tomochain/tomorelayer
  - website :: https://www.tomorelayer.com/
  - blogs :: https://medium.com/tomochain/launch-your-own-dex-with-tomorelayer-eb440a2d6a3d
  - videos :: https://www.youtube.com/watch?v=-rV2Hi165fg

+ Had fun through learning and developing some weekend projects
  - Making a with Wagtail
  - Making a template for [Nodejs full-stack application]
  - Trying out a stream-processing application with [python & kafka]
  - Researched and develop a [Tournament Scheduler] for video-game football matches between collegues in the company

** AL AHLI HOLDING GROUPS (2018 - 2019) 

#+begin_src code
Head of Technology
#+end_src

+ Guiding buiness and technology strategy across 78 discrete subsidaries
+ Managing, planning and developing all IT infrastructure conglomerate wide.
+ Creating, developing and improving the massive business intelligence and data science operations in conjunction w/ partners.
+ Acquisition due diligence, strategic planning, new and existing vertical integration planning,due diligence and implementation.
+ Strategic partner management and relationship development.
+ Mentoring and oversight of new C-Level employees and startup/new acquisition executive personnel and business development.
+ Patent strategy and patent acquisition. New patents and conceptual research related to future patents.
+ Board member of subsidiaries and related advisory and voting duties.
+ Worked closely with legal staff to develop strategic business development to maximize profitability and mitigate risk.
+ Deployed and Implemented unified CRM across 65 subsidiaries (salesforce).
+ Sample of Tech used: {Python, Java, C#, C++, ASP/.NET, Node, Agile, PHP, Ruby/ROR, unicorn/gunicorn, Docker, Flask, and many more }

* Referrences
[[https://www.linkedin.com/in/vlad-dyshko-a492a61a9/][LinkedIn]]

